# Generated by Django 5.0.6 on 2024-05-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('diameter', models.FloatField()),
                ('mass', models.FloatField()),
                ('orbit', models.CharField(max_length=255)),
                ('discovery_date', models.DateField()),
                ('potential_hazard', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Asteroids',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlackHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mass', models.FloatField()),
                ('distance_from_earth', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Black_Holes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FavoriteSpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_object_id', models.IntegerField()),
                ('object_type', models.CharField(max_length=50)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Favorite_Space_Objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.FloatField()),
                ('distance_from_earth', models.FloatField()),
                ('number_of_stars', models.BigIntegerField()),
                ('has_black_hole', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Galaxies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=50)),
                ('capture_date', models.DateField()),
                ('photo_link', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('diameter', models.FloatField()),
                ('mass', models.FloatField()),
                ('average_distance_from_sun', models.FloatField()),
                ('orbital_period', models.FloatField()),
                ('number_of_moons', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Planets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spacecraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('launch_date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Spacecrafts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpaceMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('launch_date', models.DateField()),
                ('objective', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('participating_countries', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Space_Missions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spectral_class', models.CharField(blank=True, max_length=50, null=True)),
                ('surface_temperature', models.FloatField()),
                ('luminosity', models.FloatField()),
                ('distance_from_earth', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Stars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('number_of_tickets', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ticket_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Ticket_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('interests', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
